# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dentist.ui'
#
# Created: Fri Oct 24 14:01:30 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dentistDlg(object):
    def setupUi(self, dentistDlg):
        dentistDlg.setObjectName(_fromUtf8("dentistDlg"))
        dentistDlg.resize(464, 545)
        self.layoutWidget = QtGui.QWidget(dentistDlg)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 443, 527))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.idLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.idLineEdit.setEnabled(False)
        self.idLineEdit.setMaximumSize(QtCore.QSize(61, 20))
        self.idLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.idLineEdit.setObjectName(_fromUtf8("idLineEdit"))
        self.horizontalLayout.addWidget(self.idLineEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        self.label_18.setMaximumSize(QtCore.QSize(46, 16777215))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 0, 0, 1, 1)
        self.practiceNameLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.practiceNameLineEdit.setMaxLength(80)
        self.practiceNameLineEdit.setObjectName(_fromUtf8("practiceNameLineEdit"))
        self.gridLayout_5.addWidget(self.practiceNameLineEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(46, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.lastNameLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.lastNameLineEdit.setMaxLength(80)
        self.lastNameLineEdit.setObjectName(_fromUtf8("lastNameLineEdit"))
        self.gridLayout.addWidget(self.lastNameLineEdit, 1, 0, 1, 1)
        self.firstNameLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.firstNameLineEdit.setMaxLength(24)
        self.firstNameLineEdit.setObjectName(_fromUtf8("firstNameLineEdit"))
        self.gridLayout.addWidget(self.firstNameLineEdit, 1, 1, 1, 1)
        self.titleLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.titleLineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.titleLineEdit.setMaxLength(6)
        self.titleLineEdit.setObjectName(_fromUtf8("titleLineEdit"))
        self.gridLayout.addWidget(self.titleLineEdit, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 2, 1, 1)
        self.cLastNameLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.cLastNameLineEdit.setMaxLength(80)
        self.cLastNameLineEdit.setObjectName(_fromUtf8("cLastNameLineEdit"))
        self.gridLayout.addWidget(self.cLastNameLineEdit, 3, 0, 1, 1)
        self.cFirstNameLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.cFirstNameLineEdit.setMaxLength(24)
        self.cFirstNameLineEdit.setObjectName(_fromUtf8("cFirstNameLineEdit"))
        self.gridLayout.addWidget(self.cFirstNameLineEdit, 3, 1, 1, 1)
        self.cTitleLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.cTitleLineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cTitleLineEdit.setMaxLength(6)
        self.cTitleLineEdit.setObjectName(_fromUtf8("cTitleLineEdit"))
        self.gridLayout.addWidget(self.cTitleLineEdit, 3, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 1, 1, 2, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(46, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(46, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 3, 0, 1, 1)
        self.address1LineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.address1LineEdit.setMaxLength(80)
        self.address1LineEdit.setObjectName(_fromUtf8("address1LineEdit"))
        self.gridLayout_5.addWidget(self.address1LineEdit, 3, 1, 1, 1)
        self.address2LineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.address2LineEdit.setMaxLength(80)
        self.address2LineEdit.setObjectName(_fromUtf8("address2LineEdit"))
        self.gridLayout_5.addWidget(self.address2LineEdit, 4, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 2, 1, 1)
        self.cityLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.cityLineEdit.setMaxLength(40)
        self.cityLineEdit.setObjectName(_fromUtf8("cityLineEdit"))
        self.gridLayout_2.addWidget(self.cityLineEdit, 1, 0, 1, 1)
        self.stateLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.stateLineEdit.setMaximumSize(QtCore.QSize(41, 16777215))
        self.stateLineEdit.setMaxLength(2)
        self.stateLineEdit.setObjectName(_fromUtf8("stateLineEdit"))
        self.gridLayout_2.addWidget(self.stateLineEdit, 1, 1, 1, 1)
        self.zipLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.zipLineEdit.setMaxLength(10)
        self.zipLineEdit.setObjectName(_fromUtf8("zipLineEdit"))
        self.gridLayout_2.addWidget(self.zipLineEdit, 1, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 0, 1, 1, 1)
        self.phoneLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.phoneLineEdit.setMaxLength(25)
        self.phoneLineEdit.setObjectName(_fromUtf8("phoneLineEdit"))
        self.gridLayout_3.addWidget(self.phoneLineEdit, 1, 0, 1, 1)
        self.faxLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.faxLineEdit.setMaxLength(25)
        self.faxLineEdit.setObjectName(_fromUtf8("faxLineEdit"))
        self.gridLayout_3.addWidget(self.faxLineEdit, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(12)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_2.addWidget(self.label_16)
        self.emailLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.emailLineEdit.setMaxLength(254)
        self.emailLineEdit.setObjectName(_fromUtf8("emailLineEdit"))
        self.verticalLayout_2.addWidget(self.emailLineEdit)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setHorizontalSpacing(18)
        self.gridLayout_4.setVerticalSpacing(3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 0, 0, 1, 1)
        self.dateInactivePushButton = QtGui.QPushButton(self.layoutWidget)
        self.dateInactivePushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateInactivePushButton.setObjectName(_fromUtf8("dateInactivePushButton"))
        self.gridLayout_4.addWidget(self.dateInactivePushButton, 0, 1, 1, 1)
        self.enrollDateEdit = QtGui.QDateEdit(self.layoutWidget)
        self.enrollDateEdit.setObjectName(_fromUtf8("enrollDateEdit"))
        self.gridLayout_4.addWidget(self.enrollDateEdit, 1, 0, 1, 1)
        self.dateInactiveLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.dateInactiveLineEdit.setEnabled(False)
        self.dateInactiveLineEdit.setMaximumSize(QtCore.QSize(71, 20))
        self.dateInactiveLineEdit.setMaxLength(12)
        self.dateInactiveLineEdit.setObjectName(_fromUtf8("dateInactiveLineEdit"))
        self.gridLayout_4.addWidget(self.dateInactiveLineEdit, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)
        spacerItem3 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_19 = QtGui.QLabel(self.layoutWidget)
        self.label_19.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_3.addWidget(self.label_19)
        self.commentTextEdit = QtGui.QTextEdit(self.layoutWidget)
        self.commentTextEdit.setMaximumSize(QtCore.QSize(16777215, 71))
        self.commentTextEdit.setObjectName(_fromUtf8("commentTextEdit"))
        self.verticalLayout_3.addWidget(self.commentTextEdit)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.findPushButton = QtGui.QPushButton(self.layoutWidget)
        self.findPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.findPushButton.setObjectName(_fromUtf8("findPushButton"))
        self.horizontalLayout_5.addWidget(self.findPushButton)
        self.seekFirstPushButton = QtGui.QPushButton(self.layoutWidget)
        self.seekFirstPushButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.seekFirstPushButton.setObjectName(_fromUtf8("seekFirstPushButton"))
        self.horizontalLayout_5.addWidget(self.seekFirstPushButton)
        self.seekPreviousPushButton = QtGui.QPushButton(self.layoutWidget)
        self.seekPreviousPushButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.seekPreviousPushButton.setObjectName(_fromUtf8("seekPreviousPushButton"))
        self.horizontalLayout_5.addWidget(self.seekPreviousPushButton)
        self.seekNextPushButton = QtGui.QPushButton(self.layoutWidget)
        self.seekNextPushButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.seekNextPushButton.setObjectName(_fromUtf8("seekNextPushButton"))
        self.horizontalLayout_5.addWidget(self.seekNextPushButton)
        self.seekLastPushButton = QtGui.QPushButton(self.layoutWidget)
        self.seekLastPushButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.seekLastPushButton.setObjectName(_fromUtf8("seekLastPushButton"))
        self.horizontalLayout_5.addWidget(self.seekLastPushButton)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.insertPushButton = QtGui.QPushButton(self.layoutWidget)
        self.insertPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.insertPushButton.setObjectName(_fromUtf8("insertPushButton"))
        self.horizontalLayout_4.addWidget(self.insertPushButton)
        self.modifyPushButton = QtGui.QPushButton(self.layoutWidget)
        self.modifyPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.modifyPushButton.setObjectName(_fromUtf8("modifyPushButton"))
        self.horizontalLayout_4.addWidget(self.modifyPushButton)
        self.savePushButton = QtGui.QPushButton(self.layoutWidget)
        self.savePushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.savePushButton.setObjectName(_fromUtf8("savePushButton"))
        self.horizontalLayout_4.addWidget(self.savePushButton)
        self.cancelPushButton = QtGui.QPushButton(self.layoutWidget)
        self.cancelPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.cancelPushButton.setObjectName(_fromUtf8("cancelPushButton"))
        self.horizontalLayout_4.addWidget(self.cancelPushButton)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelPushButton = QtGui.QPushButton(self.layoutWidget)
        self.labelPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.labelPushButton.setObjectName(_fromUtf8("labelPushButton"))
        self.horizontalLayout_3.addWidget(self.labelPushButton)
        self.billPushButton = QtGui.QPushButton(self.layoutWidget)
        self.billPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.billPushButton.setObjectName(_fromUtf8("billPushButton"))
        self.horizontalLayout_3.addWidget(self.billPushButton)
        self.reportPushButton = QtGui.QPushButton(self.layoutWidget)
        self.reportPushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.reportPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.reportPushButton.setObjectName(_fromUtf8("reportPushButton"))
        self.horizontalLayout_3.addWidget(self.reportPushButton)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)

        self.retranslateUi(dentistDlg)
        QtCore.QMetaObject.connectSlotsByName(dentistDlg)
        dentistDlg.setTabOrder(self.practiceNameLineEdit, self.lastNameLineEdit)
        dentistDlg.setTabOrder(self.lastNameLineEdit, self.firstNameLineEdit)
        dentistDlg.setTabOrder(self.firstNameLineEdit, self.titleLineEdit)
        dentistDlg.setTabOrder(self.titleLineEdit, self.cLastNameLineEdit)
        dentistDlg.setTabOrder(self.cLastNameLineEdit, self.cFirstNameLineEdit)
        dentistDlg.setTabOrder(self.cFirstNameLineEdit, self.cTitleLineEdit)
        dentistDlg.setTabOrder(self.cTitleLineEdit, self.address1LineEdit)
        dentistDlg.setTabOrder(self.address1LineEdit, self.address2LineEdit)
        dentistDlg.setTabOrder(self.address2LineEdit, self.cityLineEdit)
        dentistDlg.setTabOrder(self.cityLineEdit, self.stateLineEdit)
        dentistDlg.setTabOrder(self.stateLineEdit, self.zipLineEdit)
        dentistDlg.setTabOrder(self.zipLineEdit, self.phoneLineEdit)
        dentistDlg.setTabOrder(self.phoneLineEdit, self.faxLineEdit)
        dentistDlg.setTabOrder(self.faxLineEdit, self.emailLineEdit)
        dentistDlg.setTabOrder(self.emailLineEdit, self.enrollDateEdit)
        dentistDlg.setTabOrder(self.enrollDateEdit, self.commentTextEdit)
        dentistDlg.setTabOrder(self.commentTextEdit, self.dateInactivePushButton)
        dentistDlg.setTabOrder(self.dateInactivePushButton, self.idLineEdit)
        dentistDlg.setTabOrder(self.idLineEdit, self.findPushButton)
        dentistDlg.setTabOrder(self.findPushButton, self.seekFirstPushButton)
        dentistDlg.setTabOrder(self.seekFirstPushButton, self.seekPreviousPushButton)
        dentistDlg.setTabOrder(self.seekPreviousPushButton, self.seekNextPushButton)
        dentistDlg.setTabOrder(self.seekNextPushButton, self.seekLastPushButton)
        dentistDlg.setTabOrder(self.seekLastPushButton, self.insertPushButton)
        dentistDlg.setTabOrder(self.insertPushButton, self.modifyPushButton)
        dentistDlg.setTabOrder(self.modifyPushButton, self.savePushButton)
        dentistDlg.setTabOrder(self.savePushButton, self.cancelPushButton)
        dentistDlg.setTabOrder(self.cancelPushButton, self.labelPushButton)
        dentistDlg.setTabOrder(self.labelPushButton, self.billPushButton)

    def retranslateUi(self, dentistDlg):
        dentistDlg.setWindowTitle(_translate("dentistDlg", "Dialog", None))
        self.label.setText(_translate("dentistDlg", "Denstist ID", None))
        self.label_18.setText(_translate("dentistDlg", "Practice\n"
"Name", None))
        self.label_2.setText(_translate("dentistDlg", "Person In\n"
"Charge", None))
        self.label_4.setText(_translate("dentistDlg", "Last Name", None))
        self.label_5.setText(_translate("dentistDlg", "First Name", None))
        self.label_6.setText(_translate("dentistDlg", "Title", None))
        self.label_7.setText(_translate("dentistDlg", "Last Name", None))
        self.label_8.setText(_translate("dentistDlg", "First Name", None))
        self.label_9.setText(_translate("dentistDlg", "Title", None))
        self.label_3.setText(_translate("dentistDlg", "Contact\n"
"Person", None))
        self.label_10.setText(_translate("dentistDlg", "Mailing\n"
"Address", None))
        self.label_11.setText(_translate("dentistDlg", "City", None))
        self.label_12.setText(_translate("dentistDlg", "State", None))
        self.label_13.setText(_translate("dentistDlg", "Zip Code", None))
        self.label_14.setText(_translate("dentistDlg", "Phone Number", None))
        self.label_15.setText(_translate("dentistDlg", "FAX", None))
        self.label_16.setText(_translate("dentistDlg", "Email", None))
        self.label_17.setText(_translate("dentistDlg", "Enroll Date", None))
        self.dateInactivePushButton.setText(_translate("dentistDlg", "Date Inactive", None))
        self.label_19.setText(_translate("dentistDlg", "Comment", None))
        self.findPushButton.setText(_translate("dentistDlg", "&Find", None))
        self.seekFirstPushButton.setText(_translate("dentistDlg", "|<", None))
        self.seekPreviousPushButton.setText(_translate("dentistDlg", "<", None))
        self.seekNextPushButton.setText(_translate("dentistDlg", ">", None))
        self.seekLastPushButton.setText(_translate("dentistDlg", ">|", None))
        self.insertPushButton.setText(_translate("dentistDlg", "&Insert", None))
        self.modifyPushButton.setText(_translate("dentistDlg", "&Modify", None))
        self.savePushButton.setText(_translate("dentistDlg", "&Save", None))
        self.cancelPushButton.setText(_translate("dentistDlg", "&Cancel", None))
        self.labelPushButton.setText(_translate("dentistDlg", "&Label", None))
        self.billPushButton.setText(_translate("dentistDlg", "&Bill", None))
        self.reportPushButton.setText(_translate("dentistDlg", "Report", None))

