# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\lot.ui'
#
# Created: Wed Jul 30 14:54:04 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_lotDlg(object):
    def setupUi(self, lotDlg):
        lotDlg.setObjectName(_fromUtf8("lotDlg"))
        lotDlg.resize(381, 248)
        self.widget = QtGui.QWidget(lotDlg)
        self.widget.setGeometry(QtCore.QRect(14, 15, 356, 218))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.idLineEdit = QtGui.QLineEdit(self.widget)
        self.idLineEdit.setEnabled(False)
        self.idLineEdit.setMaximumSize(QtCore.QSize(51, 20))
        self.idLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.idLineEdit.setObjectName(_fromUtf8("idLineEdit"))
        self.horizontalLayout_3.addWidget(self.idLineEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 2, 1, 1)
        self.lotNameLineEdit = QtGui.QLineEdit(self.widget)
        self.lotNameLineEdit.setObjectName(_fromUtf8("lotNameLineEdit"))
        self.gridLayout_3.addWidget(self.lotNameLineEdit, 1, 0, 1, 1)
        self.receivedDateEdit = QtGui.QDateEdit(self.widget)
        self.receivedDateEdit.setObjectName(_fromUtf8("receivedDateEdit"))
        self.gridLayout_3.addWidget(self.receivedDateEdit, 1, 1, 1, 1)
        self.expirationDateEdit = QtGui.QDateEdit(self.widget)
        self.expirationDateEdit.setObjectName(_fromUtf8("expirationDateEdit"))
        self.gridLayout_3.addWidget(self.expirationDateEdit, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.lotCountSpinBox = QtGui.QSpinBox(self.widget)
        self.lotCountSpinBox.setMinimumSize(QtCore.QSize(81, 0))
        self.lotCountSpinBox.setMaximum(999999)
        self.lotCountSpinBox.setSingleStep(1000)
        self.lotCountSpinBox.setObjectName(_fromUtf8("lotCountSpinBox"))
        self.gridLayout.addWidget(self.lotCountSpinBox, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 1, 1, 1)
        self.chemicalVaporComboBox = QtGui.QComboBox(self.widget)
        self.chemicalVaporComboBox.setEnabled(False)
        self.chemicalVaporComboBox.setMinimumSize(QtCore.QSize(101, 0))
        self.chemicalVaporComboBox.setObjectName(_fromUtf8("chemicalVaporComboBox"))
        self.gridLayout.addWidget(self.chemicalVaporComboBox, 1, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        spacerItem5 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.dateInactivePushButton = QtGui.QPushButton(self.widget)
        self.dateInactivePushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateInactivePushButton.setObjectName(_fromUtf8("dateInactivePushButton"))
        self.gridLayout_2.addWidget(self.dateInactivePushButton, 0, 1, 1, 1)
        self.commentLineEdit = QtGui.QLineEdit(self.widget)
        self.commentLineEdit.setObjectName(_fromUtf8("commentLineEdit"))
        self.gridLayout_2.addWidget(self.commentLineEdit, 1, 0, 1, 1)
        self.dateInactiveLineEdit = QtGui.QLineEdit(self.widget)
        self.dateInactiveLineEdit.setEnabled(False)
        self.dateInactiveLineEdit.setMaximumSize(QtCore.QSize(91, 16777215))
        self.dateInactiveLineEdit.setObjectName(_fromUtf8("dateInactiveLineEdit"))
        self.gridLayout_2.addWidget(self.dateInactiveLineEdit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.findPushButton = QtGui.QPushButton(self.widget)
        self.findPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.findPushButton.setObjectName(_fromUtf8("findPushButton"))
        self.horizontalLayout_4.addWidget(self.findPushButton)
        self.seekFirstPushButton = QtGui.QPushButton(self.widget)
        self.seekFirstPushButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.seekFirstPushButton.setObjectName(_fromUtf8("seekFirstPushButton"))
        self.horizontalLayout_4.addWidget(self.seekFirstPushButton)
        self.seekPreviousPushButton = QtGui.QPushButton(self.widget)
        self.seekPreviousPushButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.seekPreviousPushButton.setObjectName(_fromUtf8("seekPreviousPushButton"))
        self.horizontalLayout_4.addWidget(self.seekPreviousPushButton)
        self.seekNextPushButton = QtGui.QPushButton(self.widget)
        self.seekNextPushButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.seekNextPushButton.setObjectName(_fromUtf8("seekNextPushButton"))
        self.horizontalLayout_4.addWidget(self.seekNextPushButton)
        self.seekLastPushButton = QtGui.QPushButton(self.widget)
        self.seekLastPushButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.seekLastPushButton.setObjectName(_fromUtf8("seekLastPushButton"))
        self.horizontalLayout_4.addWidget(self.seekLastPushButton)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.insertPushButton = QtGui.QPushButton(self.widget)
        self.insertPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.insertPushButton.setObjectName(_fromUtf8("insertPushButton"))
        self.horizontalLayout.addWidget(self.insertPushButton)
        self.modifyPushButton = QtGui.QPushButton(self.widget)
        self.modifyPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.modifyPushButton.setObjectName(_fromUtf8("modifyPushButton"))
        self.horizontalLayout.addWidget(self.modifyPushButton)
        self.savePushButton = QtGui.QPushButton(self.widget)
        self.savePushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.savePushButton.setObjectName(_fromUtf8("savePushButton"))
        self.horizontalLayout.addWidget(self.savePushButton)
        self.cancelPushButton = QtGui.QPushButton(self.widget)
        self.cancelPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.cancelPushButton.setObjectName(_fromUtf8("cancelPushButton"))
        self.horizontalLayout.addWidget(self.cancelPushButton)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(lotDlg)
        QtCore.QMetaObject.connectSlotsByName(lotDlg)

    def retranslateUi(self, lotDlg):
        lotDlg.setWindowTitle(_translate("lotDlg", "Dialog", None))
        self.label.setText(_translate("lotDlg", "Registered Lot ID", None))
        self.label_2.setText(_translate("lotDlg", "Lot Name", None))
        self.label_3.setText(_translate("lotDlg", "Received Date", None))
        self.label_4.setText(_translate("lotDlg", "Expiration Date", None))
        self.label_5.setText(_translate("lotDlg", "Lot Count", None))
        self.label_6.setText(_translate("lotDlg", "FDA Approved for\n"
"Chemical Vapor", None))
        self.label_7.setText(_translate("lotDlg", "Comment", None))
        self.dateInactivePushButton.setText(_translate("lotDlg", "Date Inactive", None))
        self.findPushButton.setText(_translate("lotDlg", "&Find", None))
        self.seekFirstPushButton.setText(_translate("lotDlg", "|<", None))
        self.seekPreviousPushButton.setText(_translate("lotDlg", "<", None))
        self.seekNextPushButton.setText(_translate("lotDlg", ">", None))
        self.seekLastPushButton.setText(_translate("lotDlg", ">|", None))
        self.insertPushButton.setText(_translate("lotDlg", "&Insert", None))
        self.modifyPushButton.setText(_translate("lotDlg", "&Modify", None))
        self.savePushButton.setText(_translate("lotDlg", "&Save", None))
        self.cancelPushButton.setText(_translate("lotDlg", "C&ancel", None))

