# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\paymentsummary.ui'
#
# Created: Tue Nov 18 09:39:19 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_paymentSummaryDlg(object):
    def setupUi(self, paymentSummaryDlg):
        paymentSummaryDlg.setObjectName(_fromUtf8("paymentSummaryDlg"))
        paymentSummaryDlg.resize(557, 550)
        self.widget = QtGui.QWidget(paymentSummaryDlg)
        self.widget.setGeometry(QtCore.QRect(11, 12, 530, 526))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_8.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.yearRadioButton = QtGui.QRadioButton(self.widget)
        self.yearRadioButton.setObjectName(_fromUtf8("yearRadioButton"))
        self.verticalLayout.addWidget(self.yearRadioButton)
        self.monthRadioButton = QtGui.QRadioButton(self.widget)
        self.monthRadioButton.setObjectName(_fromUtf8("monthRadioButton"))
        self.verticalLayout.addWidget(self.monthRadioButton)
        self.freeformRadioButton = QtGui.QRadioButton(self.widget)
        self.freeformRadioButton.setObjectName(_fromUtf8("freeformRadioButton"))
        self.verticalLayout.addWidget(self.freeformRadioButton)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setVerticalSpacing(1)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.prevMonthPushButton = QtGui.QPushButton(self.widget)
        self.prevMonthPushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.prevMonthPushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevMonthPushButton.setObjectName(_fromUtf8("prevMonthPushButton"))
        self.horizontalLayout_3.addWidget(self.prevMonthPushButton)
        self.monthLineEdit = QtGui.QLineEdit(self.widget)
        self.monthLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.monthLineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.monthLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.monthLineEdit.setObjectName(_fromUtf8("monthLineEdit"))
        self.horizontalLayout_3.addWidget(self.monthLineEdit)
        self.nextMonthPushButton = QtGui.QPushButton(self.widget)
        self.nextMonthPushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.nextMonthPushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.nextMonthPushButton.setObjectName(_fromUtf8("nextMonthPushButton"))
        self.horizontalLayout_3.addWidget(self.nextMonthPushButton)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.prevYearPushButton = QtGui.QPushButton(self.widget)
        self.prevYearPushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.prevYearPushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevYearPushButton.setObjectName(_fromUtf8("prevYearPushButton"))
        self.horizontalLayout.addWidget(self.prevYearPushButton)
        self.yearLineEdit = QtGui.QLineEdit(self.widget)
        self.yearLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.yearLineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.yearLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.yearLineEdit.setObjectName(_fromUtf8("yearLineEdit"))
        self.horizontalLayout.addWidget(self.yearLineEdit)
        self.nextYearPushButton = QtGui.QPushButton(self.widget)
        self.nextYearPushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.nextYearPushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.nextYearPushButton.setObjectName(_fromUtf8("nextYearPushButton"))
        self.horizontalLayout.addWidget(self.nextYearPushButton)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem3 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.beginDateEdit = QtGui.QDateEdit(self.widget)
        self.beginDateEdit.setObjectName(_fromUtf8("beginDateEdit"))
        self.horizontalLayout_10.addWidget(self.beginDateEdit)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_10.addWidget(self.label_2)
        self.endDateEdit = QtGui.QDateEdit(self.widget)
        self.endDateEdit.setObjectName(_fromUtf8("endDateEdit"))
        self.horizontalLayout_10.addWidget(self.endDateEdit)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        spacerItem4 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.previewReportPushButton = QtGui.QPushButton(self.widget)
        self.previewReportPushButton.setObjectName(_fromUtf8("previewReportPushButton"))
        self.horizontalLayout_2.addWidget(self.previewReportPushButton)
        self.viewReportPushButton = QtGui.QPushButton(self.widget)
        self.viewReportPushButton.setObjectName(_fromUtf8("viewReportPushButton"))
        self.horizontalLayout_2.addWidget(self.viewReportPushButton)
        self.exitPushButton = QtGui.QPushButton(self.widget)
        self.exitPushButton.setObjectName(_fromUtf8("exitPushButton"))
        self.horizontalLayout_2.addWidget(self.exitPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.renewalFeesPushButton = QtGui.QPushButton(self.widget)
        self.renewalFeesPushButton.setObjectName(_fromUtf8("renewalFeesPushButton"))
        self.gridLayout.addWidget(self.renewalFeesPushButton, 0, 0, 1, 1)
        self.renewalFeesLabel = QtGui.QLabel(self.widget)
        self.renewalFeesLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.renewalFeesLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.renewalFeesLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.renewalFeesLabel.setObjectName(_fromUtf8("renewalFeesLabel"))
        self.gridLayout.addWidget(self.renewalFeesLabel, 0, 1, 1, 1)
        self.renewalFeePaymentsPushButton = QtGui.QPushButton(self.widget)
        self.renewalFeePaymentsPushButton.setObjectName(_fromUtf8("renewalFeePaymentsPushButton"))
        self.gridLayout.addWidget(self.renewalFeePaymentsPushButton, 1, 0, 1, 1)
        self.renewalFeePaymentsLabel = QtGui.QLabel(self.widget)
        self.renewalFeePaymentsLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.renewalFeePaymentsLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.renewalFeePaymentsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.renewalFeePaymentsLabel.setObjectName(_fromUtf8("renewalFeePaymentsLabel"))
        self.gridLayout.addWidget(self.renewalFeePaymentsLabel, 1, 1, 1, 1)
        self.lateFeesPushButton = QtGui.QPushButton(self.widget)
        self.lateFeesPushButton.setObjectName(_fromUtf8("lateFeesPushButton"))
        self.gridLayout.addWidget(self.lateFeesPushButton, 2, 0, 1, 1)
        self.lateFeesLabel = QtGui.QLabel(self.widget)
        self.lateFeesLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.lateFeesLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lateFeesLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lateFeesLabel.setObjectName(_fromUtf8("lateFeesLabel"))
        self.gridLayout.addWidget(self.lateFeesLabel, 2, 1, 1, 1)
        self.lateFeePaymentsPushButton = QtGui.QPushButton(self.widget)
        self.lateFeePaymentsPushButton.setObjectName(_fromUtf8("lateFeePaymentsPushButton"))
        self.gridLayout.addWidget(self.lateFeePaymentsPushButton, 3, 0, 1, 1)
        self.lateFeePaymentsLabel = QtGui.QLabel(self.widget)
        self.lateFeePaymentsLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.lateFeePaymentsLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lateFeePaymentsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lateFeePaymentsLabel.setObjectName(_fromUtf8("lateFeePaymentsLabel"))
        self.gridLayout.addWidget(self.lateFeePaymentsLabel, 3, 1, 1, 1)
        self.unassignedPaymentsPushButton = QtGui.QPushButton(self.widget)
        self.unassignedPaymentsPushButton.setObjectName(_fromUtf8("unassignedPaymentsPushButton"))
        self.gridLayout.addWidget(self.unassignedPaymentsPushButton, 4, 0, 1, 1)
        self.unassignedPaymentsLabel = QtGui.QLabel(self.widget)
        self.unassignedPaymentsLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.unassignedPaymentsLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.unassignedPaymentsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unassignedPaymentsLabel.setObjectName(_fromUtf8("unassignedPaymentsLabel"))
        self.gridLayout.addWidget(self.unassignedPaymentsLabel, 4, 1, 1, 1)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 5, 1, 1, 1)
        self.balanceLabel = QtGui.QLabel(self.widget)
        self.balanceLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.balanceLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.balanceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.balanceLabel.setObjectName(_fromUtf8("balanceLabel"))
        self.gridLayout.addWidget(self.balanceLabel, 6, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.line_4 = QtGui.QFrame(self.widget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_3.addWidget(self.line_4)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 1, 6, 1, 1)
        self.renewalsIssuedPushButton = QtGui.QPushButton(self.widget)
        self.renewalsIssuedPushButton.setObjectName(_fromUtf8("renewalsIssuedPushButton"))
        self.gridLayout_4.addWidget(self.renewalsIssuedPushButton, 1, 2, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 1, 3, 1, 1)
        self.partialPaymentsPushButton = QtGui.QPushButton(self.widget)
        self.partialPaymentsPushButton.setObjectName(_fromUtf8("partialPaymentsPushButton"))
        self.gridLayout_4.addWidget(self.partialPaymentsPushButton, 1, 5, 1, 1)
        self.label_34 = QtGui.QLabel(self.widget)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_4.addWidget(self.label_34, 0, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.widget)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_4.addWidget(self.label_33, 1, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.widget)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_4.addWidget(self.label_32, 1, 4, 1, 1)
        self.testsCompletedPushButton = QtGui.QPushButton(self.widget)
        self.testsCompletedPushButton.setObjectName(_fromUtf8("testsCompletedPushButton"))
        self.gridLayout_4.addWidget(self.testsCompletedPushButton, 0, 2, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.line_5 = QtGui.QFrame(self.widget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_3.addWidget(self.line_5)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_19 = QtGui.QLabel(self.widget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 6, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.paidLabel2 = QtGui.QLabel(self.widget)
        self.paidLabel2.setMinimumSize(QtCore.QSize(70, 0))
        self.paidLabel2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.paidLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.paidLabel2.setObjectName(_fromUtf8("paidLabel2"))
        self.gridLayout_3.addWidget(self.paidLabel2, 3, 2, 1, 1)
        self.paidLabel4 = QtGui.QLabel(self.widget)
        self.paidLabel4.setMinimumSize(QtCore.QSize(70, 0))
        self.paidLabel4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.paidLabel4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.paidLabel4.setObjectName(_fromUtf8("paidLabel4"))
        self.gridLayout_3.addWidget(self.paidLabel4, 5, 2, 1, 1)
        self.paymentTotalLabel = QtGui.QLabel(self.widget)
        self.paymentTotalLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.paymentTotalLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.paymentTotalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.paymentTotalLabel.setObjectName(_fromUtf8("paymentTotalLabel"))
        self.gridLayout_3.addWidget(self.paymentTotalLabel, 8, 2, 1, 1)
        self.paidLabel5 = QtGui.QLabel(self.widget)
        self.paidLabel5.setMinimumSize(QtCore.QSize(70, 0))
        self.paidLabel5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.paidLabel5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.paidLabel5.setObjectName(_fromUtf8("paidLabel5"))
        self.gridLayout_3.addWidget(self.paidLabel5, 6, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.widget)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.widget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 7, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 5, 0, 1, 1)
        self.paidNoChargeLabel = QtGui.QLabel(self.widget)
        self.paidNoChargeLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.paidNoChargeLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.paidNoChargeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.paidNoChargeLabel.setObjectName(_fromUtf8("paidNoChargeLabel"))
        self.gridLayout_3.addWidget(self.paidNoChargeLabel, 1, 2, 1, 1)
        self.paidLabel1 = QtGui.QLabel(self.widget)
        self.paidLabel1.setMinimumSize(QtCore.QSize(70, 0))
        self.paidLabel1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.paidLabel1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.paidLabel1.setObjectName(_fromUtf8("paidLabel1"))
        self.gridLayout_3.addWidget(self.paidLabel1, 2, 2, 1, 1)
        self.paidPushButton5 = QtGui.QPushButton(self.widget)
        self.paidPushButton5.setMinimumSize(QtCore.QSize(80, 25))
        self.paidPushButton5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.paidPushButton5.setObjectName(_fromUtf8("paidPushButton5"))
        self.gridLayout_3.addWidget(self.paidPushButton5, 6, 1, 1, 1)
        self.paidPushButton1 = QtGui.QPushButton(self.widget)
        self.paidPushButton1.setMinimumSize(QtCore.QSize(80, 25))
        self.paidPushButton1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.paidPushButton1.setObjectName(_fromUtf8("paidPushButton1"))
        self.gridLayout_3.addWidget(self.paidPushButton1, 2, 1, 1, 1)
        self.paidPushButton2 = QtGui.QPushButton(self.widget)
        self.paidPushButton2.setMinimumSize(QtCore.QSize(80, 25))
        self.paidPushButton2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.paidPushButton2.setObjectName(_fromUtf8("paidPushButton2"))
        self.gridLayout_3.addWidget(self.paidPushButton2, 3, 1, 1, 1)
        self.paidLabel3 = QtGui.QLabel(self.widget)
        self.paidLabel3.setMinimumSize(QtCore.QSize(70, 0))
        self.paidLabel3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.paidLabel3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.paidLabel3.setObjectName(_fromUtf8("paidLabel3"))
        self.gridLayout_3.addWidget(self.paidLabel3, 4, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.paidPushButton3 = QtGui.QPushButton(self.widget)
        self.paidPushButton3.setMinimumSize(QtCore.QSize(80, 25))
        self.paidPushButton3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.paidPushButton3.setObjectName(_fromUtf8("paidPushButton3"))
        self.gridLayout_3.addWidget(self.paidPushButton3, 4, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.widget)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_3.addWidget(self.label_26, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 4, 0, 1, 1)
        self.paidNoChargePushButton = QtGui.QPushButton(self.widget)
        self.paidNoChargePushButton.setMinimumSize(QtCore.QSize(80, 25))
        self.paidNoChargePushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.paidNoChargePushButton.setObjectName(_fromUtf8("paidNoChargePushButton"))
        self.gridLayout_3.addWidget(self.paidNoChargePushButton, 1, 1, 1, 1)
        self.paidPushButton4 = QtGui.QPushButton(self.widget)
        self.paidPushButton4.setMinimumSize(QtCore.QSize(80, 25))
        self.paidPushButton4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.paidPushButton4.setObjectName(_fromUtf8("paidPushButton4"))
        self.gridLayout_3.addWidget(self.paidPushButton4, 5, 1, 1, 1)
        self.totalPaidPushButton = QtGui.QPushButton(self.widget)
        self.totalPaidPushButton.setObjectName(_fromUtf8("totalPaidPushButton"))
        self.gridLayout_3.addWidget(self.totalPaidPushButton, 8, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_3)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.totalUnpaidPushButton = QtGui.QPushButton(self.widget)
        self.totalUnpaidPushButton.setObjectName(_fromUtf8("totalUnpaidPushButton"))
        self.gridLayout_2.addWidget(self.totalUnpaidPushButton, 8, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.widget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 6, 0, 1, 1)
        self.unpaidLabel2 = QtGui.QLabel(self.widget)
        self.unpaidLabel2.setMinimumSize(QtCore.QSize(70, 0))
        self.unpaidLabel2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.unpaidLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unpaidLabel2.setObjectName(_fromUtf8("unpaidLabel2"))
        self.gridLayout_2.addWidget(self.unpaidLabel2, 3, 2, 1, 1)
        self.unpaidPushButton4 = QtGui.QPushButton(self.widget)
        self.unpaidPushButton4.setMinimumSize(QtCore.QSize(80, 25))
        self.unpaidPushButton4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.unpaidPushButton4.setObjectName(_fromUtf8("unpaidPushButton4"))
        self.gridLayout_2.addWidget(self.unpaidPushButton4, 5, 1, 1, 1)
        self.unpaidLabel3 = QtGui.QLabel(self.widget)
        self.unpaidLabel3.setMinimumSize(QtCore.QSize(70, 0))
        self.unpaidLabel3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.unpaidLabel3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unpaidLabel3.setObjectName(_fromUtf8("unpaidLabel3"))
        self.gridLayout_2.addWidget(self.unpaidLabel3, 4, 2, 1, 1)
        self.unpaidPushButton3 = QtGui.QPushButton(self.widget)
        self.unpaidPushButton3.setMinimumSize(QtCore.QSize(80, 25))
        self.unpaidPushButton3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.unpaidPushButton3.setObjectName(_fromUtf8("unpaidPushButton3"))
        self.gridLayout_2.addWidget(self.unpaidPushButton3, 4, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.widget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.widget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 4, 0, 1, 1)
        self.unpaidLabel5 = QtGui.QLabel(self.widget)
        self.unpaidLabel5.setMinimumSize(QtCore.QSize(70, 0))
        self.unpaidLabel5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.unpaidLabel5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unpaidLabel5.setObjectName(_fromUtf8("unpaidLabel5"))
        self.gridLayout_2.addWidget(self.unpaidLabel5, 6, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.widget)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 0, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.widget)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 0, 1, 1, 1)
        self.unpaidPushButton1 = QtGui.QPushButton(self.widget)
        self.unpaidPushButton1.setMinimumSize(QtCore.QSize(80, 25))
        self.unpaidPushButton1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.unpaidPushButton1.setObjectName(_fromUtf8("unpaidPushButton1"))
        self.gridLayout_2.addWidget(self.unpaidPushButton1, 2, 1, 1, 1)
        self.line_3 = QtGui.QFrame(self.widget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.line_3, 7, 2, 1, 1)
        self.outstandingBalanceTotalLabel = QtGui.QLabel(self.widget)
        self.outstandingBalanceTotalLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.outstandingBalanceTotalLabel.setMaximumSize(QtCore.QSize(70, 16777215))
        self.outstandingBalanceTotalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outstandingBalanceTotalLabel.setObjectName(_fromUtf8("outstandingBalanceTotalLabel"))
        self.gridLayout_2.addWidget(self.outstandingBalanceTotalLabel, 8, 2, 1, 1)
        self.unpaidLabel4 = QtGui.QLabel(self.widget)
        self.unpaidLabel4.setMinimumSize(QtCore.QSize(70, 0))
        self.unpaidLabel4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.unpaidLabel4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unpaidLabel4.setObjectName(_fromUtf8("unpaidLabel4"))
        self.gridLayout_2.addWidget(self.unpaidLabel4, 5, 2, 1, 1)
        self.unpaidPushButton2 = QtGui.QPushButton(self.widget)
        self.unpaidPushButton2.setMinimumSize(QtCore.QSize(80, 25))
        self.unpaidPushButton2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.unpaidPushButton2.setObjectName(_fromUtf8("unpaidPushButton2"))
        self.gridLayout_2.addWidget(self.unpaidPushButton2, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.unpaidLabel1 = QtGui.QLabel(self.widget)
        self.unpaidLabel1.setMinimumSize(QtCore.QSize(70, 0))
        self.unpaidLabel1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.unpaidLabel1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unpaidLabel1.setObjectName(_fromUtf8("unpaidLabel1"))
        self.gridLayout_2.addWidget(self.unpaidLabel1, 2, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.widget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 5, 0, 1, 1)
        self.unpaidPushButton5 = QtGui.QPushButton(self.widget)
        self.unpaidPushButton5.setMinimumSize(QtCore.QSize(80, 25))
        self.unpaidPushButton5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.unpaidPushButton5.setObjectName(_fromUtf8("unpaidPushButton5"))
        self.gridLayout_2.addWidget(self.unpaidPushButton5, 6, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_2)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)

        self.retranslateUi(paymentSummaryDlg)
        QtCore.QMetaObject.connectSlotsByName(paymentSummaryDlg)

    def retranslateUi(self, paymentSummaryDlg):
        paymentSummaryDlg.setWindowTitle(_translate("paymentSummaryDlg", "Dialog", None))
        self.label.setText(_translate("paymentSummaryDlg", "Choose period by:", None))
        self.yearRadioButton.setText(_translate("paymentSummaryDlg", "Year", None))
        self.monthRadioButton.setText(_translate("paymentSummaryDlg", "Month", None))
        self.freeformRadioButton.setText(_translate("paymentSummaryDlg", "Free-form", None))
        self.label_3.setText(_translate("paymentSummaryDlg", "Month", None))
        self.label_5.setText(_translate("paymentSummaryDlg", "Year", None))
        self.prevMonthPushButton.setText(_translate("paymentSummaryDlg", "<", None))
        self.nextMonthPushButton.setText(_translate("paymentSummaryDlg", ">", None))
        self.prevYearPushButton.setText(_translate("paymentSummaryDlg", "<", None))
        self.nextYearPushButton.setText(_translate("paymentSummaryDlg", ">", None))
        self.label_2.setText(_translate("paymentSummaryDlg", "to", None))
        self.previewReportPushButton.setText(_translate("paymentSummaryDlg", "&Preview Data", None))
        self.viewReportPushButton.setText(_translate("paymentSummaryDlg", "&View Report", None))
        self.exitPushButton.setText(_translate("paymentSummaryDlg", "E&xit", None))
        self.renewalFeesPushButton.setText(_translate("paymentSummaryDlg", "Renewal Fees:", None))
        self.renewalFeesLabel.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.renewalFeePaymentsPushButton.setText(_translate("paymentSummaryDlg", "Payments:", None))
        self.renewalFeePaymentsLabel.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.lateFeesPushButton.setText(_translate("paymentSummaryDlg", "Late Fees:", None))
        self.lateFeesLabel.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.lateFeePaymentsPushButton.setText(_translate("paymentSummaryDlg", "Late Fee Payments:", None))
        self.lateFeePaymentsLabel.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.unassignedPaymentsPushButton.setText(_translate("paymentSummaryDlg", "Unassigned:", None))
        self.unassignedPaymentsLabel.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.balanceLabel.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.label_7.setText(_translate("paymentSummaryDlg", "Balance:", None))
        self.renewalsIssuedPushButton.setText(_translate("paymentSummaryDlg", "PushButton", None))
        self.partialPaymentsPushButton.setText(_translate("paymentSummaryDlg", "PushButton", None))
        self.label_34.setText(_translate("paymentSummaryDlg", "Tests completed:", None))
        self.label_33.setText(_translate("paymentSummaryDlg", "Renewals Issued:", None))
        self.label_32.setText(_translate("paymentSummaryDlg", "Partial Payments Received:", None))
        self.testsCompletedPushButton.setText(_translate("paymentSummaryDlg", "PushButton", None))
        self.label_19.setText(_translate("paymentSummaryDlg", "120+ days", None))
        self.label_12.setText(_translate("paymentSummaryDlg", "(No Charge)", None))
        self.paidLabel2.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.paidLabel4.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.paymentTotalLabel.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.paidLabel5.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.label_28.setText(_translate("paymentSummaryDlg", "Payment Total", None))
        self.label_10.setText(_translate("paymentSummaryDlg", "30-59 days", None))
        self.label_13.setText(_translate("paymentSummaryDlg", "90 - 119 days", None))
        self.paidNoChargeLabel.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.paidLabel1.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.paidPushButton5.setText(_translate("paymentSummaryDlg", "PushButton", None))
        self.paidPushButton1.setText(_translate("paymentSummaryDlg", "PushButton", None))
        self.paidPushButton2.setText(_translate("paymentSummaryDlg", "PushButton", None))
        self.paidLabel3.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.label_4.setText(_translate("paymentSummaryDlg", "0-29 days", None))
        self.paidPushButton3.setText(_translate("paymentSummaryDlg", "PushButton", None))
        self.label_26.setText(_translate("paymentSummaryDlg", "N Paid", None))
        self.label_11.setText(_translate("paymentSummaryDlg", "60-89 days", None))
        self.paidNoChargePushButton.setText(_translate("paymentSummaryDlg", "PushButton", None))
        self.paidPushButton4.setText(_translate("paymentSummaryDlg", "PushButton", None))
        self.totalPaidPushButton.setText(_translate("paymentSummaryDlg", "PushButton", None))
        self.totalUnpaidPushButton.setText(_translate("paymentSummaryDlg", "PushButton", None))
        self.label_20.setText(_translate("paymentSummaryDlg", "120+ days", None))
        self.unpaidLabel2.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.unpaidPushButton4.setText(_translate("paymentSummaryDlg", "PushButton", None))
        self.unpaidLabel3.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.unpaidPushButton3.setText(_translate("paymentSummaryDlg", "PushButton", None))
        self.label_16.setText(_translate("paymentSummaryDlg", "30-59 days", None))
        self.label_15.setText(_translate("paymentSummaryDlg", "60-89 days", None))
        self.unpaidLabel5.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.label_29.setText(_translate("paymentSummaryDlg", "Balance", None))
        self.label_27.setText(_translate("paymentSummaryDlg", "N Unpaid", None))
        self.unpaidPushButton1.setText(_translate("paymentSummaryDlg", "PushButton", None))
        self.outstandingBalanceTotalLabel.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.unpaidLabel4.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.unpaidPushButton2.setText(_translate("paymentSummaryDlg", "PushButton", None))
        self.label_6.setText(_translate("paymentSummaryDlg", "0-29 days", None))
        self.unpaidLabel1.setText(_translate("paymentSummaryDlg", "TextLabel", None))
        self.label_14.setText(_translate("paymentSummaryDlg", "90 - 119 days", None))
        self.unpaidPushButton5.setText(_translate("paymentSummaryDlg", "PushButton", None))

