# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\renewal.ui'
#
# Created: Fri Oct 24 15:22:00 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_renewalDlg(object):
    def setupUi(self, renewalDlg):
        renewalDlg.setObjectName(_fromUtf8("renewalDlg"))
        renewalDlg.resize(550, 536)
        self.widget = QtGui.QWidget(renewalDlg)
        self.widget.setGeometry(QtCore.QRect(14, 14, 525, 519))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.idLineEdit = QtGui.QLineEdit(self.widget)
        self.idLineEdit.setEnabled(False)
        self.idLineEdit.setMaximumSize(QtCore.QSize(91, 16777215))
        self.idLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.idLineEdit.setObjectName(_fromUtf8("idLineEdit"))
        self.horizontalLayout.addWidget(self.idLineEdit)
        spacerItem1 = QtGui.QSpacerItem(218, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 16, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_12.addWidget(self.label_2)
        self.lotNameLineEdit = QtGui.QLineEdit(self.widget)
        self.lotNameLineEdit.setEnabled(False)
        self.lotNameLineEdit.setMinimumSize(QtCore.QSize(130, 0))
        self.lotNameLineEdit.setMaximumSize(QtCore.QSize(150, 20))
        self.lotNameLineEdit.setObjectName(_fromUtf8("lotNameLineEdit"))
        self.verticalLayout_12.addWidget(self.lotNameLineEdit)
        self.horizontalLayout_9.addLayout(self.verticalLayout_12)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_10.addWidget(self.label_3)
        self.renewalDateLineEdit = QtGui.QLineEdit(self.widget)
        self.renewalDateLineEdit.setEnabled(False)
        self.renewalDateLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.renewalDateLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.renewalDateLineEdit.setObjectName(_fromUtf8("renewalDateLineEdit"))
        self.verticalLayout_10.addWidget(self.renewalDateLineEdit)
        self.horizontalLayout_9.addLayout(self.verticalLayout_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.renewalFeeSpinBox = QtGui.QDoubleSpinBox(self.widget)
        self.renewalFeeSpinBox.setMinimumSize(QtCore.QSize(80, 0))
        self.renewalFeeSpinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.renewalFeeSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.renewalFeeSpinBox.setMaximum(9999.99)
        self.renewalFeeSpinBox.setSingleStep(5.0)
        self.renewalFeeSpinBox.setObjectName(_fromUtf8("renewalFeeSpinBox"))
        self.gridLayout_2.addWidget(self.renewalFeeSpinBox, 1, 0, 1, 1)
        self.waivePushButton = QtGui.QPushButton(self.widget)
        self.waivePushButton.setMaximumSize(QtCore.QSize(60, 20))
        self.waivePushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.waivePushButton.setObjectName(_fromUtf8("waivePushButton"))
        self.gridLayout_2.addWidget(self.waivePushButton, 1, 2, 1, 1)
        self.lateFeeSpinBox = QtGui.QDoubleSpinBox(self.widget)
        self.lateFeeSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lateFeeSpinBox.setMaximum(999.0)
        self.lateFeeSpinBox.setSingleStep(5.0)
        self.lateFeeSpinBox.setObjectName(_fromUtf8("lateFeeSpinBox"))
        self.gridLayout_2.addWidget(self.lateFeeSpinBox, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_7.addWidget(self.label_6)
        self.datePaidLineEdit = QtGui.QLineEdit(self.widget)
        self.datePaidLineEdit.setMaximumSize(QtCore.QSize(80, 20))
        self.datePaidLineEdit.setObjectName(_fromUtf8("datePaidLineEdit"))
        self.verticalLayout_7.addWidget(self.datePaidLineEdit)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_6.addWidget(self.label_8)
        self.checkNumLineEdit = QtGui.QLineEdit(self.widget)
        self.checkNumLineEdit.setMinimumSize(QtCore.QSize(130, 0))
        self.checkNumLineEdit.setMaximumSize(QtCore.QSize(150, 20))
        self.checkNumLineEdit.setObjectName(_fromUtf8("checkNumLineEdit"))
        self.verticalLayout_6.addWidget(self.checkNumLineEdit)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_13.addWidget(self.label_4)
        self.numTestsLineEdit = QtGui.QLineEdit(self.widget)
        self.numTestsLineEdit.setEnabled(False)
        self.numTestsLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.numTestsLineEdit.setObjectName(_fromUtf8("numTestsLineEdit"))
        self.verticalLayout_13.addWidget(self.numTestsLineEdit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_13 = QtGui.QLabel(self.widget)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_5.addWidget(self.label_13)
        self.amountDueSpinBox = QtGui.QDoubleSpinBox(self.widget)
        self.amountDueSpinBox.setEnabled(False)
        self.amountDueSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.amountDueSpinBox.setMaximum(9999.99)
        self.amountDueSpinBox.setObjectName(_fromUtf8("amountDueSpinBox"))
        self.verticalLayout_5.addWidget(self.amountDueSpinBox)
        self.verticalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_4.addWidget(self.label_7)
        self.amountPaidSpinBox = QtGui.QDoubleSpinBox(self.widget)
        self.amountPaidSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.amountPaidSpinBox.setMaximum(9999.99)
        self.amountPaidSpinBox.setSingleStep(5.0)
        self.amountPaidSpinBox.setObjectName(_fromUtf8("amountPaidSpinBox"))
        self.verticalLayout_4.addWidget(self.amountPaidSpinBox)
        self.verticalLayout_11.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.dateInactivePushButton = QtGui.QPushButton(self.widget)
        self.dateInactivePushButton.setMaximumSize(QtCore.QSize(80, 20))
        self.dateInactivePushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateInactivePushButton.setObjectName(_fromUtf8("dateInactivePushButton"))
        self.verticalLayout_8.addWidget(self.dateInactivePushButton)
        self.dateInactiveLineEdit = QtGui.QLineEdit(self.widget)
        self.dateInactiveLineEdit.setEnabled(False)
        self.dateInactiveLineEdit.setMaximumSize(QtCore.QSize(80, 20))
        self.dateInactiveLineEdit.setObjectName(_fromUtf8("dateInactiveLineEdit"))
        self.verticalLayout_8.addWidget(self.dateInactiveLineEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.commentTextEdit = QtGui.QTextEdit(self.widget)
        self.commentTextEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.commentTextEdit.setMaximumSize(QtCore.QSize(503, 71))
        self.commentTextEdit.setObjectName(_fromUtf8("commentTextEdit"))
        self.verticalLayout.addWidget(self.commentTextEdit)
        self.verticalLayout_9.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.historyLabel = QtGui.QLabel(self.widget)
        self.historyLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.historyLabel.setObjectName(_fromUtf8("historyLabel"))
        self.verticalLayout_3.addWidget(self.historyLabel)
        self.historyTableWidget = QtGui.QTableWidget(self.widget)
        self.historyTableWidget.setEnabled(True)
        self.historyTableWidget.setMinimumSize(QtCore.QSize(503, 0))
        self.historyTableWidget.setMaximumSize(QtCore.QSize(503, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        self.historyTableWidget.setFont(font)
        self.historyTableWidget.setObjectName(_fromUtf8("historyTableWidget"))
        self.verticalLayout_3.addWidget(self.historyTableWidget)
        self.verticalLayout_9.addLayout(self.verticalLayout_3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.findPushButton = QtGui.QPushButton(self.widget)
        self.findPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.findPushButton.setObjectName(_fromUtf8("findPushButton"))
        self.horizontalLayout_4.addWidget(self.findPushButton)
        self.seekFirstPushButton = QtGui.QPushButton(self.widget)
        self.seekFirstPushButton.setMaximumSize(QtCore.QSize(31, 16777215))
        self.seekFirstPushButton.setObjectName(_fromUtf8("seekFirstPushButton"))
        self.horizontalLayout_4.addWidget(self.seekFirstPushButton)
        self.seekPreviousPushButton = QtGui.QPushButton(self.widget)
        self.seekPreviousPushButton.setMaximumSize(QtCore.QSize(31, 16777215))
        self.seekPreviousPushButton.setObjectName(_fromUtf8("seekPreviousPushButton"))
        self.horizontalLayout_4.addWidget(self.seekPreviousPushButton)
        self.seekNextPushButton = QtGui.QPushButton(self.widget)
        self.seekNextPushButton.setMaximumSize(QtCore.QSize(31, 16777215))
        self.seekNextPushButton.setObjectName(_fromUtf8("seekNextPushButton"))
        self.horizontalLayout_4.addWidget(self.seekNextPushButton)
        self.seekLastPushButton = QtGui.QPushButton(self.widget)
        self.seekLastPushButton.setMaximumSize(QtCore.QSize(31, 16777215))
        self.seekLastPushButton.setObjectName(_fromUtf8("seekLastPushButton"))
        self.horizontalLayout_4.addWidget(self.seekLastPushButton)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.startPushButton = QtGui.QPushButton(self.widget)
        self.startPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.startPushButton.setObjectName(_fromUtf8("startPushButton"))
        self.horizontalLayout_3.addWidget(self.startPushButton)
        self.sendPushButton = QtGui.QPushButton(self.widget)
        self.sendPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.sendPushButton.setObjectName(_fromUtf8("sendPushButton"))
        self.horizontalLayout_3.addWidget(self.sendPushButton)
        self.payPushButton = QtGui.QPushButton(self.widget)
        self.payPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.payPushButton.setObjectName(_fromUtf8("payPushButton"))
        self.horizontalLayout_3.addWidget(self.payPushButton)
        self.savePushButton = QtGui.QPushButton(self.widget)
        self.savePushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.savePushButton.setObjectName(_fromUtf8("savePushButton"))
        self.horizontalLayout_3.addWidget(self.savePushButton)
        self.cancelPushButton = QtGui.QPushButton(self.widget)
        self.cancelPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.cancelPushButton.setObjectName(_fromUtf8("cancelPushButton"))
        self.horizontalLayout_3.addWidget(self.cancelPushButton)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelPushButton = QtGui.QPushButton(self.widget)
        self.labelPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.labelPushButton.setObjectName(_fromUtf8("labelPushButton"))
        self.horizontalLayout_6.addWidget(self.labelPushButton)
        self.billPushButton = QtGui.QPushButton(self.widget)
        self.billPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.billPushButton.setObjectName(_fromUtf8("billPushButton"))
        self.horizontalLayout_6.addWidget(self.billPushButton)
        self.reportPushButton = QtGui.QPushButton(self.widget)
        self.reportPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.reportPushButton.setObjectName(_fromUtf8("reportPushButton"))
        self.horizontalLayout_6.addWidget(self.reportPushButton)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)

        self.retranslateUi(renewalDlg)
        QtCore.QMetaObject.connectSlotsByName(renewalDlg)

    def retranslateUi(self, renewalDlg):
        renewalDlg.setWindowTitle(_translate("renewalDlg", "Dialog", None))
        self.label.setText(_translate("renewalDlg", "Renewal ID", None))
        self.label_2.setText(_translate("renewalDlg", "Lot Name", None))
        self.label_3.setText(_translate("renewalDlg", "Renewal Date", None))
        self.label_5.setText(_translate("renewalDlg", "Renewal Fee", None))
        self.label_9.setText(_translate("renewalDlg", "Late Fee", None))
        self.renewalFeeSpinBox.setPrefix(_translate("renewalDlg", "$", None))
        self.waivePushButton.setText(_translate("renewalDlg", "Waive", None))
        self.lateFeeSpinBox.setPrefix(_translate("renewalDlg", "$", None))
        self.label_6.setText(_translate("renewalDlg", "Paid Date", None))
        self.label_8.setText(_translate("renewalDlg", "Check Number", None))
        self.label_4.setText(_translate("renewalDlg", "Tests Sent", None))
        self.label_13.setText(_translate("renewalDlg", "Amount Due", None))
        self.amountDueSpinBox.setPrefix(_translate("renewalDlg", "$", None))
        self.label_7.setText(_translate("renewalDlg", "Amount Paid", None))
        self.amountPaidSpinBox.setPrefix(_translate("renewalDlg", "$", None))
        self.dateInactivePushButton.setText(_translate("renewalDlg", "Date Inactive", None))
        self.label_10.setText(_translate("renewalDlg", "Comment", None))
        self.historyLabel.setText(_translate("renewalDlg", "Renewal History for Sterilizer", None))
        self.findPushButton.setText(_translate("renewalDlg", "&Find", None))
        self.seekFirstPushButton.setText(_translate("renewalDlg", "<<", None))
        self.seekPreviousPushButton.setText(_translate("renewalDlg", "<", None))
        self.seekNextPushButton.setText(_translate("renewalDlg", ">", None))
        self.seekLastPushButton.setText(_translate("renewalDlg", ">>", None))
        self.startPushButton.setText(_translate("renewalDlg", "S&tart", None))
        self.sendPushButton.setText(_translate("renewalDlg", "S&end", None))
        self.payPushButton.setText(_translate("renewalDlg", "&Pay", None))
        self.savePushButton.setText(_translate("renewalDlg", "&Save", None))
        self.cancelPushButton.setText(_translate("renewalDlg", "C&ancel", None))
        self.labelPushButton.setText(_translate("renewalDlg", "&Label", None))
        self.billPushButton.setText(_translate("renewalDlg", "&Bill", None))
        self.reportPushButton.setText(_translate("renewalDlg", "&Report", None))

