# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sterilizer.ui'
#
# Created: Sat Oct 11 17:43:37 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_sterilizerDlg(object):
    def setupUi(self, sterilizerDlg):
        sterilizerDlg.setObjectName(_fromUtf8("sterilizerDlg"))
        sterilizerDlg.resize(467, 284)
        self.widget = QtGui.QWidget(sterilizerDlg)
        self.widget.setGeometry(QtCore.QRect(10, 10, 443, 261))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.idLineEdit = QtGui.QLineEdit(self.widget)
        self.idLineEdit.setEnabled(False)
        self.idLineEdit.setMaximumSize(QtCore.QSize(61, 20))
        self.idLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.idLineEdit.setObjectName(_fromUtf8("idLineEdit"))
        self.horizontalLayout_2.addWidget(self.idLineEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.renewalTestSpinBox = QtGui.QSpinBox(self.widget)
        self.renewalTestSpinBox.setObjectName(_fromUtf8("renewalTestSpinBox"))
        self.gridLayout_3.addWidget(self.renewalTestSpinBox, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 3, 1, 1)
        self.renewalFeeSpinBox = QtGui.QDoubleSpinBox(self.widget)
        self.renewalFeeSpinBox.setMinimumSize(QtCore.QSize(91, 0))
        self.renewalFeeSpinBox.setMaximum(999.99)
        self.renewalFeeSpinBox.setSingleStep(5.0)
        self.renewalFeeSpinBox.setObjectName(_fromUtf8("renewalFeeSpinBox"))
        self.gridLayout_3.addWidget(self.renewalFeeSpinBox, 1, 3, 1, 1)
        self.enrollDateEdit = QtGui.QDateEdit(self.widget)
        self.enrollDateEdit.setObjectName(_fromUtf8("enrollDateEdit"))
        self.gridLayout_3.addWidget(self.enrollDateEdit, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 2, 1, 1)
        self.numTestsSpinBox = QtGui.QSpinBox(self.widget)
        self.numTestsSpinBox.setObjectName(_fromUtf8("numTestsSpinBox"))
        self.gridLayout_3.addWidget(self.numTestsSpinBox, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.methodComboBox = QtGui.QComboBox(self.widget)
        self.methodComboBox.setMinimumSize(QtCore.QSize(131, 0))
        self.methodComboBox.setObjectName(_fromUtf8("methodComboBox"))
        self.gridLayout_2.addWidget(self.methodComboBox, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.modelLineEdit = QtGui.QLineEdit(self.widget)
        self.modelLineEdit.setMaxLength(50)
        self.modelLineEdit.setObjectName(_fromUtf8("modelLineEdit"))
        self.gridLayout_2.addWidget(self.modelLineEdit, 1, 1, 1, 1)
        self.serialNumLineEdit = QtGui.QLineEdit(self.widget)
        self.serialNumLineEdit.setMaxLength(20)
        self.serialNumLineEdit.setObjectName(_fromUtf8("serialNumLineEdit"))
        self.gridLayout_2.addWidget(self.serialNumLineEdit, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.commentLineEdit = QtGui.QLineEdit(self.widget)
        self.commentLineEdit.setMaxLength(120)
        self.commentLineEdit.setObjectName(_fromUtf8("commentLineEdit"))
        self.verticalLayout.addWidget(self.commentLineEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dateInactiveLineEdit = QtGui.QLineEdit(self.widget)
        self.dateInactiveLineEdit.setEnabled(False)
        self.dateInactiveLineEdit.setMaximumSize(QtCore.QSize(91, 16777215))
        self.dateInactiveLineEdit.setMaxLength(12)
        self.dateInactiveLineEdit.setObjectName(_fromUtf8("dateInactiveLineEdit"))
        self.gridLayout.addWidget(self.dateInactiveLineEdit, 1, 0, 1, 1)
        self.dateInactivePushButton = QtGui.QPushButton(self.widget)
        self.dateInactivePushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateInactivePushButton.setObjectName(_fromUtf8("dateInactivePushButton"))
        self.gridLayout.addWidget(self.dateInactivePushButton, 0, 0, 1, 1)
        self.suspendRenewalsCheckBox = QtGui.QCheckBox(self.widget)
        self.suspendRenewalsCheckBox.setObjectName(_fromUtf8("suspendRenewalsCheckBox"))
        self.gridLayout.addWidget(self.suspendRenewalsCheckBox, 1, 1, 1, 1)
        self.timeToRenewCheckBox = QtGui.QCheckBox(self.widget)
        self.timeToRenewCheckBox.setObjectName(_fromUtf8("timeToRenewCheckBox"))
        self.gridLayout.addWidget(self.timeToRenewCheckBox, 0, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.findPushButton = QtGui.QPushButton(self.widget)
        self.findPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.findPushButton.setObjectName(_fromUtf8("findPushButton"))
        self.horizontalLayout_5.addWidget(self.findPushButton)
        self.seekFirstPushButton = QtGui.QPushButton(self.widget)
        self.seekFirstPushButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.seekFirstPushButton.setObjectName(_fromUtf8("seekFirstPushButton"))
        self.horizontalLayout_5.addWidget(self.seekFirstPushButton)
        self.seekPreviousPushButton = QtGui.QPushButton(self.widget)
        self.seekPreviousPushButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.seekPreviousPushButton.setObjectName(_fromUtf8("seekPreviousPushButton"))
        self.horizontalLayout_5.addWidget(self.seekPreviousPushButton)
        self.seekNextPushButton = QtGui.QPushButton(self.widget)
        self.seekNextPushButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.seekNextPushButton.setObjectName(_fromUtf8("seekNextPushButton"))
        self.horizontalLayout_5.addWidget(self.seekNextPushButton)
        self.seekLastPushButton = QtGui.QPushButton(self.widget)
        self.seekLastPushButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.seekLastPushButton.setObjectName(_fromUtf8("seekLastPushButton"))
        self.horizontalLayout_5.addWidget(self.seekLastPushButton)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.insertPushButton = QtGui.QPushButton(self.widget)
        self.insertPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.insertPushButton.setObjectName(_fromUtf8("insertPushButton"))
        self.horizontalLayout.addWidget(self.insertPushButton)
        self.modifyPushButton = QtGui.QPushButton(self.widget)
        self.modifyPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.modifyPushButton.setObjectName(_fromUtf8("modifyPushButton"))
        self.horizontalLayout.addWidget(self.modifyPushButton)
        self.savePushButton = QtGui.QPushButton(self.widget)
        self.savePushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.savePushButton.setObjectName(_fromUtf8("savePushButton"))
        self.horizontalLayout.addWidget(self.savePushButton)
        self.cancelPushButton = QtGui.QPushButton(self.widget)
        self.cancelPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.cancelPushButton.setObjectName(_fromUtf8("cancelPushButton"))
        self.horizontalLayout.addWidget(self.cancelPushButton)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelPushButton = QtGui.QPushButton(self.widget)
        self.labelPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.labelPushButton.setObjectName(_fromUtf8("labelPushButton"))
        self.horizontalLayout_6.addWidget(self.labelPushButton)
        self.billPushButton = QtGui.QPushButton(self.widget)
        self.billPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.billPushButton.setObjectName(_fromUtf8("billPushButton"))
        self.horizontalLayout_6.addWidget(self.billPushButton)
        self.reportPushButton = QtGui.QPushButton(self.widget)
        self.reportPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.reportPushButton.setObjectName(_fromUtf8("reportPushButton"))
        self.horizontalLayout_6.addWidget(self.reportPushButton)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)

        self.retranslateUi(sterilizerDlg)
        QtCore.QMetaObject.connectSlotsByName(sterilizerDlg)

    def retranslateUi(self, sterilizerDlg):
        sterilizerDlg.setWindowTitle(_translate("sterilizerDlg", "Dialog", None))
        self.label.setText(_translate("sterilizerDlg", "Sterilizer ID", None))
        self.label_2.setText(_translate("sterilizerDlg", "Enroll Date", None))
        self.label_5.setText(_translate("sterilizerDlg", "Renewal Fee", None))
        self.renewalFeeSpinBox.setPrefix(_translate("sterilizerDlg", "$", None))
        self.label_3.setText(_translate("sterilizerDlg", "Number\n"
"of Tests", None))
        self.label_4.setText(_translate("sterilizerDlg", "Renewal\n"
"Test", None))
        self.label_8.setText(_translate("sterilizerDlg", "Sterilizing Method", None))
        self.label_7.setText(_translate("sterilizerDlg", "Model", None))
        self.label_6.setText(_translate("sterilizerDlg", "Serial Number", None))
        self.label_9.setText(_translate("sterilizerDlg", "Comment", None))
        self.dateInactivePushButton.setText(_translate("sterilizerDlg", "Date Inactive", None))
        self.suspendRenewalsCheckBox.setText(_translate("sterilizerDlg", "Suspend Renewals", None))
        self.timeToRenewCheckBox.setText(_translate("sterilizerDlg", "Time to Renew", None))
        self.findPushButton.setText(_translate("sterilizerDlg", "&Find", None))
        self.seekFirstPushButton.setText(_translate("sterilizerDlg", "|<", None))
        self.seekPreviousPushButton.setText(_translate("sterilizerDlg", "<", None))
        self.seekNextPushButton.setText(_translate("sterilizerDlg", ">", None))
        self.seekLastPushButton.setText(_translate("sterilizerDlg", ">|", None))
        self.insertPushButton.setText(_translate("sterilizerDlg", "&Insert", None))
        self.modifyPushButton.setText(_translate("sterilizerDlg", "&Modify", None))
        self.savePushButton.setText(_translate("sterilizerDlg", "&Save", None))
        self.cancelPushButton.setText(_translate("sterilizerDlg", "&Cancel", None))
        self.labelPushButton.setText(_translate("sterilizerDlg", "&Label", None))
        self.billPushButton.setText(_translate("sterilizerDlg", "&Bill", None))
        self.reportPushButton.setText(_translate("sterilizerDlg", "Report", None))

