# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\test.ui'
#
# Created: Wed Dec 03 14:55:09 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_testDlg(object):
    def setupUi(self, testDlg):
        testDlg.setObjectName(_fromUtf8("testDlg"))
        testDlg.resize(502, 517)
        testDlg.setMinimumSize(QtCore.QSize(0, 0))
        testDlg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.layoutWidget = QtGui.QWidget(testDlg)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 19, 479, 487))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(13, 19, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.renewalIdLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.renewalIdLineEdit.setEnabled(False)
        self.renewalIdLineEdit.setMaximumSize(QtCore.QSize(91, 20))
        self.renewalIdLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.renewalIdLineEdit.setObjectName(_fromUtf8("renewalIdLineEdit"))
        self.gridLayout.addWidget(self.renewalIdLineEdit, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.testNumLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.testNumLineEdit.setEnabled(False)
        self.testNumLineEdit.setMaximumSize(QtCore.QSize(31, 16777215))
        self.testNumLineEdit.setObjectName(_fromUtf8("testNumLineEdit"))
        self.horizontalLayout_2.addWidget(self.testNumLineEdit)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.maxTestNumLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.maxTestNumLineEdit.setEnabled(False)
        self.maxTestNumLineEdit.setMaximumSize(QtCore.QSize(31, 16777215))
        self.maxTestNumLineEdit.setObjectName(_fromUtf8("maxTestNumLineEdit"))
        self.horizontalLayout_2.addWidget(self.maxTestNumLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 4, 1, 1)
        self.renewalDateEdit = QtGui.QLineEdit(self.layoutWidget)
        self.renewalDateEdit.setEnabled(False)
        self.renewalDateEdit.setMaximumSize(QtCore.QSize(70, 20))
        self.renewalDateEdit.setObjectName(_fromUtf8("renewalDateEdit"))
        self.gridLayout.addWidget(self.renewalDateEdit, 1, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 19, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 6, 1, 1)
        self.stripNumLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.stripNumLineEdit.setEnabled(True)
        self.stripNumLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.stripNumLineEdit.setObjectName(_fromUtf8("stripNumLineEdit"))
        self.gridLayout.addWidget(self.stripNumLineEdit, 1, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setMinimumSize(QtCore.QSize(30, 0))
        self.label_15.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 0, 2, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 1, 1, 1)
        self.prevDayPushButton = QtGui.QPushButton(self.layoutWidget)
        self.prevDayPushButton.setMaximumSize(QtCore.QSize(40, 20))
        self.prevDayPushButton.setObjectName(_fromUtf8("prevDayPushButton"))
        self.gridLayout_3.addWidget(self.prevDayPushButton, 1, 0, 1, 1)
        self.sterilizeDateEdit = QtGui.QDateEdit(self.layoutWidget)
        self.sterilizeDateEdit.setMinimumSize(QtCore.QSize(90, 0))
        self.sterilizeDateEdit.setMaximumSize(QtCore.QSize(90, 16777215))
        self.sterilizeDateEdit.setObjectName(_fromUtf8("sterilizeDateEdit"))
        self.gridLayout_3.addWidget(self.sterilizeDateEdit, 1, 1, 1, 1)
        self.nextDayPushButton = QtGui.QPushButton(self.layoutWidget)
        self.nextDayPushButton.setMaximumSize(QtCore.QSize(40, 20))
        self.nextDayPushButton.setObjectName(_fromUtf8("nextDayPushButton"))
        self.gridLayout_3.addWidget(self.nextDayPushButton, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.suppliedPushButton = QtGui.QPushButton(self.layoutWidget)
        self.suppliedPushButton.setEnabled(False)
        self.suppliedPushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.suppliedPushButton.setObjectName(_fromUtf8("suppliedPushButton"))
        self.horizontalLayout_7.addWidget(self.suppliedPushButton)
        self.omittedPushButton = QtGui.QPushButton(self.layoutWidget)
        self.omittedPushButton.setEnabled(False)
        self.omittedPushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.omittedPushButton.setObjectName(_fromUtf8("omittedPushButton"))
        self.horizontalLayout_7.addWidget(self.omittedPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.startDateLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.startDateLineEdit.setMaximumSize(QtCore.QSize(70, 20))
        self.startDateLineEdit.setObjectName(_fromUtf8("startDateLineEdit"))
        self.verticalLayout_4.addWidget(self.startDateLineEdit)
        self.verticalLayout_12.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.resultDateLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.resultDateLineEdit.setMaximumSize(QtCore.QSize(70, 20))
        self.resultDateLineEdit.setObjectName(_fromUtf8("resultDateLineEdit"))
        self.verticalLayout.addWidget(self.resultDateLineEdit)
        self.verticalLayout_12.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_5.addWidget(self.label_14)
        self.startedByLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.startedByLineEdit.setMaximumSize(QtCore.QSize(75, 16777215))
        self.startedByLineEdit.setText(_fromUtf8(""))
        self.startedByLineEdit.setObjectName(_fromUtf8("startedByLineEdit"))
        self.verticalLayout_5.addWidget(self.startedByLineEdit)
        self.verticalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_6.addWidget(self.label_12)
        self.resultsByLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.resultsByLineEdit.setMaximumSize(QtCore.QSize(75, 16777215))
        self.resultsByLineEdit.setText(_fromUtf8(""))
        self.resultsByLineEdit.setObjectName(_fromUtf8("resultsByLineEdit"))
        self.verticalLayout_6.addWidget(self.resultsByLineEdit)
        self.verticalLayout_11.addLayout(self.verticalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.testResultPushButton = QtGui.QPushButton(self.layoutWidget)
        self.testResultPushButton.setMaximumSize(QtCore.QSize(40, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.testResultPushButton.setFont(font)
        self.testResultPushButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.testResultPushButton.setText(_fromUtf8(""))
        self.testResultPushButton.setDefault(False)
        self.testResultPushButton.setFlat(False)
        self.testResultPushButton.setObjectName(_fromUtf8("testResultPushButton"))
        self.gridLayout_2.addWidget(self.testResultPushButton, 1, 0, 1, 1)
        self.controlResultPushButton = QtGui.QPushButton(self.layoutWidget)
        self.controlResultPushButton.setMaximumSize(QtCore.QSize(40, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.controlResultPushButton.setFont(font)
        self.controlResultPushButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.controlResultPushButton.setText(_fromUtf8(""))
        self.controlResultPushButton.setFlat(False)
        self.controlResultPushButton.setObjectName(_fromUtf8("controlResultPushButton"))
        self.gridLayout_2.addWidget(self.controlResultPushButton, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_14.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_14)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_8.addWidget(self.label_11)
        self.commentTextEdit = QtGui.QTextEdit(self.layoutWidget)
        self.commentTextEdit.setMinimumSize(QtCore.QSize(431, 0))
        self.commentTextEdit.setMaximumSize(QtCore.QSize(16777215, 71))
        self.commentTextEdit.setObjectName(_fromUtf8("commentTextEdit"))
        self.verticalLayout_8.addWidget(self.commentTextEdit)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_7.addWidget(self.label_13)
        self.historyTableWidget = QtGui.QTableWidget(self.layoutWidget)
        self.historyTableWidget.setMaximumSize(QtCore.QSize(16777215, 192))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        self.historyTableWidget.setFont(font)
        self.historyTableWidget.setObjectName(_fromUtf8("historyTableWidget"))
        self.verticalLayout_7.addWidget(self.historyTableWidget)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.findPushButton = QtGui.QPushButton(self.layoutWidget)
        self.findPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.findPushButton.setObjectName(_fromUtf8("findPushButton"))
        self.horizontalLayout_5.addWidget(self.findPushButton)
        self.seekFirstPushButton = QtGui.QPushButton(self.layoutWidget)
        self.seekFirstPushButton.setMaximumSize(QtCore.QSize(31, 16777215))
        self.seekFirstPushButton.setObjectName(_fromUtf8("seekFirstPushButton"))
        self.horizontalLayout_5.addWidget(self.seekFirstPushButton)
        self.seekPreviousPushButton = QtGui.QPushButton(self.layoutWidget)
        self.seekPreviousPushButton.setMaximumSize(QtCore.QSize(31, 16777215))
        self.seekPreviousPushButton.setObjectName(_fromUtf8("seekPreviousPushButton"))
        self.horizontalLayout_5.addWidget(self.seekPreviousPushButton)
        self.seekNextPushButton = QtGui.QPushButton(self.layoutWidget)
        self.seekNextPushButton.setMaximumSize(QtCore.QSize(31, 16777215))
        self.seekNextPushButton.setObjectName(_fromUtf8("seekNextPushButton"))
        self.horizontalLayout_5.addWidget(self.seekNextPushButton)
        self.seekLastPushButton = QtGui.QPushButton(self.layoutWidget)
        self.seekLastPushButton.setMaximumSize(QtCore.QSize(31, 16777215))
        self.seekLastPushButton.setObjectName(_fromUtf8("seekLastPushButton"))
        self.horizontalLayout_5.addWidget(self.seekLastPushButton)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.startPushButton = QtGui.QPushButton(self.layoutWidget)
        self.startPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.startPushButton.setObjectName(_fromUtf8("startPushButton"))
        self.horizontalLayout_3.addWidget(self.startPushButton)
        self.resultPushButton = QtGui.QPushButton(self.layoutWidget)
        self.resultPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.resultPushButton.setObjectName(_fromUtf8("resultPushButton"))
        self.horizontalLayout_3.addWidget(self.resultPushButton)
        self.modifyPushButton = QtGui.QPushButton(self.layoutWidget)
        self.modifyPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.modifyPushButton.setObjectName(_fromUtf8("modifyPushButton"))
        self.horizontalLayout_3.addWidget(self.modifyPushButton)
        self.savePushButton = QtGui.QPushButton(self.layoutWidget)
        self.savePushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.savePushButton.setObjectName(_fromUtf8("savePushButton"))
        self.horizontalLayout_3.addWidget(self.savePushButton)
        self.cancelPushButton = QtGui.QPushButton(self.layoutWidget)
        self.cancelPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.cancelPushButton.setObjectName(_fromUtf8("cancelPushButton"))
        self.horizontalLayout_3.addWidget(self.cancelPushButton)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.notifyPushButton = QtGui.QPushButton(self.layoutWidget)
        self.notifyPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.notifyPushButton.setObjectName(_fromUtf8("notifyPushButton"))
        self.horizontalLayout_4.addWidget(self.notifyPushButton)
        self.reportPushButton = QtGui.QPushButton(self.layoutWidget)
        self.reportPushButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.reportPushButton.setObjectName(_fromUtf8("reportPushButton"))
        self.horizontalLayout_4.addWidget(self.reportPushButton)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)

        self.retranslateUi(testDlg)
        QtCore.QMetaObject.connectSlotsByName(testDlg)

    def retranslateUi(self, testDlg):
        testDlg.setWindowTitle(_translate("testDlg", "Dialog", None))
        self.label.setText(_translate("testDlg", "Renewal ID", None))
        self.label_2.setText(_translate("testDlg", "Test Number", None))
        self.label_4.setText(_translate("testDlg", "Renewal Date", None))
        self.label_3.setText(_translate("testDlg", "of", None))
        self.label_15.setText(_translate("testDlg", "Strip", None))
        self.label_5.setText(_translate("testDlg", "Sterilize Date", None))
        self.prevDayPushButton.setText(_translate("testDlg", "<", None))
        self.nextDayPushButton.setText(_translate("testDlg", ">", None))
        self.suppliedPushButton.setText(_translate("testDlg", "Su&pplied", None))
        self.omittedPushButton.setText(_translate("testDlg", "&Omitted", None))
        self.label_6.setText(_translate("testDlg", "Start Date", None))
        self.label_10.setText(_translate("testDlg", "Result Date", None))
        self.label_14.setText(_translate("testDlg", "Started By", None))
        self.label_12.setText(_translate("testDlg", "Results By", None))
        self.label_7.setText(_translate("testDlg", "Results", None))
        self.label_8.setText(_translate("testDlg", "Test", None))
        self.label_9.setText(_translate("testDlg", "Control", None))
        self.label_11.setText(_translate("testDlg", "Comment", None))
        self.label_13.setText(_translate("testDlg", "History", None))
        self.findPushButton.setText(_translate("testDlg", "&Find", None))
        self.seekFirstPushButton.setText(_translate("testDlg", "<<", None))
        self.seekPreviousPushButton.setText(_translate("testDlg", "<", None))
        self.seekNextPushButton.setText(_translate("testDlg", ">", None))
        self.seekLastPushButton.setText(_translate("testDlg", ">>", None))
        self.startPushButton.setText(_translate("testDlg", "S&tart", None))
        self.resultPushButton.setText(_translate("testDlg", "&Result", None))
        self.modifyPushButton.setText(_translate("testDlg", "&Modify", None))
        self.savePushButton.setText(_translate("testDlg", "&Save", None))
        self.cancelPushButton.setText(_translate("testDlg", "C&ancel", None))
        self.notifyPushButton.setText(_translate("testDlg", "&Notify", None))
        self.reportPushButton.setText(_translate("testDlg", "R&eport", None))

