# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\testcount.ui'
#
# Created: Mon Oct 27 15:55:59 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_testCountDlg(object):
    def setupUi(self, testCountDlg):
        testCountDlg.setObjectName(_fromUtf8("testCountDlg"))
        testCountDlg.resize(346, 299)
        self.widget = QtGui.QWidget(testCountDlg)
        self.widget.setGeometry(QtCore.QRect(10, 12, 322, 272))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem = QtGui.QSpacerItem(18, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.label = QtGui.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_9.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(18, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(18, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.prevPushButton = QtGui.QPushButton(self.widget)
        self.prevPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.prevPushButton.setObjectName(_fromUtf8("prevPushButton"))
        self.horizontalLayout_3.addWidget(self.prevPushButton)
        self.dateEdit = QtGui.QDateEdit(self.widget)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_3.addWidget(self.dateEdit)
        self.nextPushButton = QtGui.QPushButton(self.widget)
        self.nextPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.nextPushButton.setObjectName(_fromUtf8("nextPushButton"))
        self.horizontalLayout_3.addWidget(self.nextPushButton)
        self.todayPushButton = QtGui.QPushButton(self.widget)
        self.todayPushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.todayPushButton.setObjectName(_fromUtf8("todayPushButton"))
        self.horizontalLayout_3.addWidget(self.todayPushButton)
        spacerItem3 = QtGui.QSpacerItem(18, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_3 = QtGui.QFrame(self.widget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.inPushButton = QtGui.QPushButton(self.widget)
        self.inPushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.inPushButton.setObjectName(_fromUtf8("inPushButton"))
        self.gridLayout.addWidget(self.inPushButton, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.outPushButton = QtGui.QPushButton(self.widget)
        self.outPushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.outPushButton.setObjectName(_fromUtf8("outPushButton"))
        self.horizontalLayout_2.addWidget(self.outPushButton)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.positivesPushButton = QtGui.QPushButton(self.widget)
        self.positivesPushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.positivesPushButton.setObjectName(_fromUtf8("positivesPushButton"))
        self.horizontalLayout_2.addWidget(self.positivesPushButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 2, 1, 1)
        self.resultsPushButton = QtGui.QPushButton(self.widget)
        self.resultsPushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.resultsPushButton.setObjectName(_fromUtf8("resultsPushButton"))
        self.gridLayout.addWidget(self.resultsPushButton, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.noResultsPushButton = QtGui.QPushButton(self.widget)
        self.noResultsPushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.noResultsPushButton.setObjectName(_fromUtf8("noResultsPushButton"))
        self.gridLayout.addWidget(self.noResultsPushButton, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.overduePushButton = QtGui.QPushButton(self.widget)
        self.overduePushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.overduePushButton.setObjectName(_fromUtf8("overduePushButton"))
        self.horizontalLayout.addWidget(self.overduePushButton)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtGui.QFrame(self.widget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.closePushButton = QtGui.QPushButton(self.widget)
        self.closePushButton.setObjectName(_fromUtf8("closePushButton"))
        self.horizontalLayout_4.addWidget(self.closePushButton)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(testCountDlg)
        QtCore.QMetaObject.connectSlotsByName(testCountDlg)

    def retranslateUi(self, testCountDlg):
        testCountDlg.setWindowTitle(_translate("testCountDlg", "Dialog", None))
        self.label.setText(_translate("testCountDlg", "Count for day of:", None))
        self.prevPushButton.setText(_translate("testCountDlg", "<", None))
        self.nextPushButton.setText(_translate("testCountDlg", ">", None))
        self.todayPushButton.setText(_translate("testCountDlg", "Today", None))
        self.label_2.setText(_translate("testCountDlg", "Log counts for the day:", None))
        self.label_4.setText(_translate("testCountDlg", "In:", None))
        self.inPushButton.setText(_translate("testCountDlg", "(In)", None))
        self.label_6.setText(_translate("testCountDlg", "Out:", None))
        self.outPushButton.setText(_translate("testCountDlg", "(Out)", None))
        self.label_7.setText(_translate("testCountDlg", "Positives:", None))
        self.positivesPushButton.setText(_translate("testCountDlg", "(Positives)", None))
        self.resultsPushButton.setText(_translate("testCountDlg", "(Results)", None))
        self.label_3.setText(_translate("testCountDlg", "tests logged in that day have results", None))
        self.noResultsPushButton.setText(_translate("testCountDlg", "(NoResults)", None))
        self.label_8.setText(_translate("testCountDlg", "tests logged in that day are awaiting results", None))
        self.label_5.setText(_translate("testCountDlg", "Tests overdue for results (all days):", None))
        self.overduePushButton.setText(_translate("testCountDlg", "(Overdue)", None))
        self.closePushButton.setText(_translate("testCountDlg", "&Close", None))

